import {
	AudioLines as AudioLinesIcon,
	BadgeCent as BadgeCentIcon,
	Bike as BikeIcon,
	Code as CodeIcon,
	Dumbbell as DumbbellIcon,
	Gamepad2 as Gamepad2Icon,
	GraduationCap as GraduationCapIcon,
	Home as HomeIcon,
	Laugh as LaughIcon,
	MonitorPlay as MonitorPlayIcon,
	Music as MusicIcon,
	Radio as RadioIcon,
	Shirt as ShirtIcon,
	SmilePlus as SmilePlusIcon,
} from "lucide-react";

export const categories = [
	{ name: "New", icon: <HomeIcon size={20} /> },
	{ name: "Coding", icon: <CodeIcon size={20} /> },
	{ name: "Music", icon: <MusicIcon size={20} /> },
	{ name: "Education", icon: <GraduationCapIcon size={20} /> },
	{ name: "Podcast", icon: <AudioLinesIcon size={20} /> },
	{ name: "Movie", icon: <MonitorPlayIcon size={20} /> },
	{ name: "Gaming", icon: <Gamepad2Icon size={20} /> },
	{ name: "Live", icon: <RadioIcon size={20} /> },
	{ name: "Sport", icon: <BikeIcon size={20} /> },
	{ name: "Fashion", icon: <ShirtIcon size={20} /> },
	{ name: "Beauty", icon: <SmilePlusIcon size={20} /> },
	{ name: "Comedy", icon: <LaughIcon size={20} /> },
	{ name: "Gym", icon: <DumbbellIcon size={20} /> },
	{ name: "Crypto", icon: <BadgeCentIcon size={20} /> },
];
